@startuml(id=SystemContext)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title TAC Portal - System Context
caption An example of a System Context diagram.

Person_Ext(1, "Auction Attendee", "A member of the general public")
Person_Ext(2, "Auctioneer", "An auctioneer runs the auctions, accepting bids")
Person_Ext(3, "Tenant Admin", "Tenant Administrator")
package "The Auction Collective" {
  Person(4, "TAC Administrator", "TAC Administrator")
  System(5, "TAC Portal", "The Auction Collective Portal")
}
Rel_D(1, 5, "Registers", "")
Rel_D(1, 5, "Bids", "")
Rel_D(1, 5, "Pays", "")
Rel_D(2, 5, "Uses", "")
Rel_D(4, 5, "Uses", "")
Rel_D(3, 5, "Uses", "")
@enduml